enabled: true # выключить логи - false
level: INFO
log_dir: logs
filename: app.log
rotate_megabytes: 10
backup_count: 5

dictConfig:
  version: 1
  disable_existing_loggers: false

  formatters:
    simple:
      format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    verbose:
      format: "%(asctime)s [%(levelname)s] pid=%(process)d tid=%(thread)d %(name)s %(module)s:%(lineno)d — %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout

    rotating_file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: verbose
      filename: logs/app.log
      maxBytes: 10485760
      backupCount: 5
      encoding: utf-8

  loggers:
    scraper.author_today:  # src/Author_Today.py
      level: DEBUG
      handlers: [rotating_file, console]
      propagate: false

    scraper.litnet: # src/litnet.py
      level: DEBUG
      handlers: [rotating_file, console]
      propagate: false

    scraper.litnet_api: # src/litnet_api.py
      level: DEBUG
      handlers: [rotating_file, console]
      propagate: false

    scraper.litnet_unique_tags:  # src/litnet_unique_tags.py
      level: DEBUG
      handlers: [rotating_file, console]
      propagate: false

    scraper.litnet_xml: # src/litnet_xml.py
      level: DEBUG
      handlers: [rotating_file, console]
      propagate: false

    eda.final: # data/processed/final.py
      level: INFO
      handlers: [rotating_file, console]
      propagate: false

    notebooks.merge: # notebooks/merge.ipynb
      level: INFO
      handlers: [rotating_file, console]
      propagate: false

  root:
    level: INFO
    handlers: [rotating_file, console]
